sudo: required
services:
  - docker

before_install:
  - docker build -t kweiwang/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kweiwang/react-test npm test -- --coverage

after_success:
  - docker build -t kweiwang/multi-client ./client
  - docker build -t kweiwang/multi-nginx ./nginx
  - docker build -t kweiwang/multi-server ./server
  - docker build -t kweiwang/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kweiwang/multi-client
  - docker push kweiwang/multi-nginx
  - docker push kweiwang/multi-server
  - docker push kweiwang/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: Multi-docker-01
  env: MultiDocker-01-env
  bucket_name: elasticbeanstalk-us-west-1-087659596915
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
